# Generated by Django 3.0.6 on 2020-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
    ]
