# Generated by Django 3.0.6 on 2020-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0004_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
